# .github/workflows/concat.yml in your aggregator repo
name: Fetch + Concatenate PDFs

on:
  workflow_dispatch:

jobs:
  concat:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}   # must have repo/read rights

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Fetch PDF from repo 巻頭
        run: |
          gh auth login --with-token <<< "$GH_TOKEN"
          # get the latest successful run id for the "ci" workflow
          RUN_ID=$(gh run list --repo sozysozbot/nclc_paper_dictionary_opening --workflow ci.yml --limit 1 --json databaseId --jq '.[0].databaseId')
          gh run download $RUN_ID --repo sozysozbot/nclc_paper_dictionary_opening --name pdf-artifact --dir ./巻頭

      - name: Fetch PDF from repo 燐字辞書
        run: |
          RUN_ID=$(gh run list --repo sozysozbot/linzklar_paper_dictionary --workflow ci.yml --limit 1 --json databaseId --jq '.[0].databaseId')
          gh run download  $RUN_ID --repo sozysozbot/linzklar_paper_dictionary --name pdf-artifact --dir ./燐字辞書

      - name: Fetch PDF from repo 巻中
        run: |
          RUN_ID=$(gh run list --repo sozysozbot/nclc_paper_dictionary_middle --workflow ci.yml --limit 1 --json databaseId --jq '.[0].databaseId')
          gh run download $RUN_ID --repo sozysozbot/nclc_paper_dictionary_middle --name pdf-artifact --dir ./巻中

      - name: Fetch PDF from repo 東島通商語辞書
        run: |
          RUN_ID=$(gh run list --repo sozysozbot/pmcp_50on --workflow ci.yml --limit 1 --json databaseId --jq '.[0].databaseId')
          gh run download $RUN_ID --repo sozysozbot/pmcp_50on --name pdf-artifact --dir ./東島通商語辞書

      - name: Install pdftk
        run: |
          sudo apt-get update
          sudo apt-get install -y pdftk

      - name: Concatenate into combined.pdf
        run: |
          pdftk 巻頭/言将机戦人等_網別言書_始.pdf 燐字辞書/言将机戦人等_網別清字言書.pdf 巻中/言将机戦人等_網別言書_別.pdf 東島通商語辞書/nclc-leti-tectelit-leti-pmcp-lukup-cet.pdf cat output combined.pdf

      - name: Upload the combined PDF
        uses: actions/upload-artifact@v4
        with:
          name: combined-pdf
          path: combined.pdf
