# .github/workflows/concat.yml in your aggregator repo
name: Fetch + Concatenate PDFs

on:
  workflow_dispatch:

jobs:
  concat:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}   # must have repo/read rights

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Fetch PDF from repo 巻頭
        run: |
          gh auth login --with-token <<< "$GH_TOKEN"
          gh run download --repo sozysozbot/nclc_paper_dictionary_opening --dir ./巻頭

      - name: Fetch PDF from repo 燐字辞書
        run: |
          gh run download  --repo sozysozbot/linzklar_paper_dictionary --dir ./燐字辞書

      - name: Fetch PDF from repo 巻中
        run: |
          gh run download --repo sozysozbot/nclc_paper_dictionary_middle --dir ./巻中

      - name: Fetch PDF from repo 東島通商語辞書
        run: |
          gh run download --repo sozysozbot/pmcp_50on --dir ./東島通商語辞書

      - name: Install pdftk
        run: |
          sudo apt-get update
          sudo apt-get install -y pdftk

      - name: Concatenate into combined.pdf
        run: |
          pdftk ./巻頭/言将机戦人等_網別言書_始.pdf ./燐字辞書/言将机戦人等_網別清字言書.pdf ./巻中/言将机戦人等_網別言書_別.pdf ./東島通商語辞書/nclc-leti-tectelit-leti-pmcp-lukup-cet.pdf cat output combined.pdf

      - name: Upload the combined PDF
        uses: actions/upload-artifact@v4
        with:
          name: combined-pdf
          path: combined.pdf
